

name: Copy File
run-name: ${{ github.workflow }} run by ${{ github.actor }}
on:
  push:
    branches:
      - projects
  workflow_dispatch:
jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4
        with:
          path: projects
      
      - name: Checkout other repo
        uses: actions/checkout@v4
        with:
          repository: TheSilverLeopard/Portfolio
          path: portfolio
          token: ${{ secrets.ACTION_TOKEN }}

      - name: Copy
        run: |
          ls;
          cp -rf ./projects/Portfolio/out/* ./portfolio;

      - name: git commands
        env:
            GH_TOKEN: ${{ secrets.ACTION_TOKEN }}
        run: |
          cd ./portfolio;
          git config user.name "TheSilverLeopard";
          git config user.email "jeb.jug@gmail.com";
          git add .;
          git commit -m "update";
          git push origin HEAD;
